const steps=[...document.querySelectorAll('.step')];
const state=JSON.parse(localStorage.getItem('aiCoachState')||'{}');
state.logs=state.logs||[];state.feedback=state.feedback||{};state.finalAnswers=state.finalAnswers||{};state.meetingStatements=state.meetingStatements||[];
let current=state.current||0;let selectedSlot=state.selectedSlot||'';let meetingStage=0;
const $=id=>document.getElementById(id);const save=()=>{state.current=current;state.selectedSlot=selectedSlot;localStorage.setItem('aiCoachState',JSON.stringify(state));};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function addBubble(role,text){const div=document.createElement('div');div.className=`bubble ${role}`;div.innerHTML=`<b>${role==='ai'?'AIコーチャー':role==='boss'?'上司':'本人'}</b><span>${esc(text)}</span>`;(current===0?$('dailyChat'):$('meetingChat')).appendChild(div);div.scrollIntoView({behavior:'smooth',block:'nearest'});}
function render(){steps.forEach((s,i)=>s.classList.toggle('active',i===current));$('stepTitle').textContent=steps[current].dataset.title;$('stepCounter').textContent=`${current+1} / ${steps.length}`;$('progressFill').style.width=`${(current+1)/steps.length*100}%`;$('prevBtn').disabled=current===0;$('nextBtn').textContent=current===steps.length-1?'最初へ':'次へ';$('navMessage').textContent='';renderMemo();if(current===2)renderDashboard();if(current===3)renderReasons();if(current===9)renderFeedback();save();window.scrollTo({top:0,behavior:'smooth'});}
function renderMemo(){const f=state.feedback[current]||{};$('testMemo').value=f.memo||'';document.querySelectorAll('.reactions button').forEach(b=>b.classList.toggle('selected',b.dataset.reaction===f.reaction));}
function storeMemo(){state.feedback[current]={...(state.feedback[current]||{}),memo:$('testMemo').value};save();}
function validate(){const msg=m=>($('navMessage').textContent=m,false);if(current===0&&!state.consult)return msg('相談文を入力してから次へ進んでください');if(current===4&&(!selectedSlot||!state.meetingPurpose))return msg('面談日時と相談目的を入力してください');return true;}
function next(skip=false){storeMemo();if(!skip&&!validate())return;current=current===steps.length-1?0:current+1;render();}function prev(){storeMemo();if(current>0){current--;render();}}
$('nextBtn').onclick=()=>next(false);$('skipBtn').onclick=()=>next(true);$('prevBtn').onclick=prev;document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')next(false);if(e.key==='ArrowLeft')prev();});$('testMemo').addEventListener('input',storeMemo);document.querySelectorAll('.reactions button').forEach(b=>b.onclick=()=>{state.feedback[current]={...(state.feedback[current]||{}),reaction:b.dataset.reaction};save();renderMemo();});
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{$('consultInput').value=b.dataset.fill;});$('sendConsult').onclick=()=>{const v=$('consultInput').value.trim();if(!v)return;$('dailyChat').innerHTML='';addBubble('me',v);let reply='相談内容を確認しました。今の状況では、まず“何に迷っているか”と“判断に必要な材料”を分けて整理するとよさそうです。この相談は今日の業務ログに記録します。';if(/突発|遅れ|忙しい|時間/.test(v))reply='突発業務や遅れが発生している場合は、本人の努力不足ではなく、業務量や優先順位の問題として整理する必要があります。後で上司とすり合わせられるよう、背景も記録しておきます。';addBubble('ai',reply);state.consult=v;$('dailyToast').hidden=false;save();};
$('addLog').onclick=()=>{state.effort=$('effortInput').value.trim();state.trouble=$('troubleInput').value.trim();if(state.effort||state.trouble)state.logs.push({effort:state.effort,trouble:state.trouble});renderLogs();$('logAiComment').textContent=/遅れ|突発|忙しい|時間/.test(state.trouble||'')?'突発対応や時間不足が記録されています。スケジュール影響が続く場合、上司とのすり合わせ候補として扱います。':'本人の補足として、成果と背景を記録しました。';save();};
function renderLogs(){$('personalLogs').classList.remove('muted');$('personalLogs').innerHTML=state.logs.length?state.logs.map(l=>`<div class="log-item"><b>頑張ったこと：</b>${esc(l.effort||'未入力')}<br><b>困ったこと：</b>${esc(l.trouble||'未入力')}</div>`).join(''):'まだ追加されていません';}
function renderDashboard(){$('dashboardReflections').innerHTML=`<h2>入力内容の反映</h2><p><b>相談：</b>${esc(state.consult||'未入力')}</p><p><b>頑張ったこと：</b>${esc(state.effort||'未入力')}</p><p><b>困ったこと：</b>${esc(state.trouble||'未入力')}</p>`;}
function renderReasons(){const extra=[state.consult&&`相談内容「${state.consult}」が記録されている`,state.trouble&&`困りごと「${state.trouble}」が記録されている`].filter(Boolean);$('proposalReasons').innerHTML=['突発業務が増えている','優先順位判断で迷う場面が続いている','本人の努力や背景が見えにくくなる前に共有した方がよい',...extra].map(x=>`<li>${esc(x)}</li>`).join('');}
$('acceptMeeting').onclick=()=>{$('proposalToast').textContent='面談設定へ進めます。';$('proposalToast').hidden=false;};$('declineMeeting').onclick=()=>{$('declineBox').classList.remove('hidden');};$('declineReason').oninput=e=>{state.declineReason=e.target.value;save();};
document.querySelectorAll('.slot').forEach(b=>b.onclick=()=>{selectedSlot=b.textContent;document.querySelectorAll('.slot').forEach(s=>s.classList.toggle('selected',s===b));save();});$('confirmSchedule').onclick=()=>{state.meetingPurpose=$('meetingPurpose').value.trim();$('scheduleComplete').classList.remove('hidden');$('scheduleComplete').innerHTML=`<h2>3者面談を設定しました</h2><p><b>参加者：</b>本人、上司、AIコーチャー</p><p><b>目的：</b>${esc(state.meetingPurpose||'未入力')}</p><p><b>日時：</b>${esc(selectedSlot||'未選択')}</p>`;save();};
function docHtml(){return `<h2>相談資料</h2><section><h3>1. 現在の状況</h3><ul><li>新サービス企画資料の作成が進行中</li><li>直近2週間で突発業務が複数発生</li><li>${esc(state.trouble||'困りごとは未入力')}</li></ul></section><section><h3>2. 本人の行動</h3><ul><li>会議で論点整理を実施</li><li>関係者調整を前倒しで実施</li><li>${esc(state.effort||'頑張ったことは未入力')}</li></ul></section><section><h3>3. 困りごと</h3><ul><li>突発業務により作業時間が分断されている</li><li>優先順位の判断に迷っている</li><li>${esc(state.meetingPurpose||'相談目的は未入力')}</li></ul></section><section><h3>4. AIからの提案</h3><ul><li>突発業務の優先順位を上司とすり合わせる</li><li>資料の完成範囲を再定義する</li><li>次の2週間は判断基準を明確にする</li></ul></section>`;}
$('generateDoc').onclick=()=>{$('docCard').innerHTML=docHtml();$('docCard').classList.remove('hidden');$('editDoc').classList.remove('hidden');$('goMeeting').classList.remove('hidden');};$('editDoc').onclick=()=>{$('docEditor').value=$('docCard').innerText;$('docEditBox').classList.remove('hidden');};$('goMeeting').onclick=()=>{current=6;render();};
$('startMeeting').onclick=()=>{meetingStage=0;$('meetingChat').innerHTML='';$('startMeeting').classList.add('hidden');$('nextSpeech').classList.remove('hidden');addBubble('ai','本日の目的は、最近の業務状況を整理し、今後の進め方を合意することです。');};$('nextSpeech').onclick=()=>{if(meetingStage===0){addBubble('boss','資料作成が少し遅れているようだけど、何が原因ですか？');$('meetingInputBox').classList.remove('hidden');$('nextSpeech').classList.add('hidden');meetingStage=1;}else if(meetingStage===2){['なるほど。遅れの背景が分かりました。突発対応もかなりしてくれていたんですね。','ここからは、今後の進め方について相談します。相談テーマは、突発業務の優先順位、資料完成範囲、報告タイミングです。','まず突発業務については、発生時点で優先度を一緒に確認しましょう。タイムリーに報告してくれてありがとう。'].forEach((t,i)=>addBubble(i===1?'ai':'boss',t));$('meetingInputLabel').textContent='上司に確認したいことを入力してください';$('meetingInput').value='';$('meetingInput').placeholder='例：資料をどこまで完成させるべきか確認したい';$('meetingInputBox').classList.remove('hidden');$('nextSpeech').classList.add('hidden');meetingStage=3;}else if(meetingStage===4){addBubble('boss','今回は意思決定に必要な判断軸とおすすめ案を優先しましょう。詳細資料は次の段階で大丈夫です。');addBubble('ai','合意事項として、資料は判断軸とおすすめ案を優先、突発業務は発生時に優先度を確認、遅れが見えたら早めに相談、で記録します。');$('nextSpeech').classList.add('hidden');$('finishMeeting').classList.remove('hidden');}};
$('speakBtn').onclick=()=>{const v=$('meetingInput').value.trim();if(!v)return;addBubble('me',v);state.meetingStatements.push(v);$('assistBtn').classList.remove('hidden');save();};$('assistBtn').onclick=()=>{const last=state.meetingStatements.at(-1)||'';addBubble('ai',meetingStage===1?'補足します。直近2週間で突発業務が複数記録されており、作業時間の分断が発生しています。一方で、会議での論点整理や関係者調整は継続して実施されています。':`確認したい点は「${last}」です。資料の完成範囲と突発業務が入った時の優先順位を明確にしたい、という相談として整理します。`);$('meetingInputBox').classList.add('hidden');$('assistBtn').classList.add('hidden');$('nextSpeech').classList.remove('hidden');meetingStage=meetingStage===1?2:4;};$('finishMeeting').onclick=()=>{current=7;render();};
$('saveAgreement').onclick=()=>{state.agreement=$('agreementMemo').value;$('agreementToast').hidden=false;save();};
function reportHtml(){return `<h2>件名：現時点の成長・貢献レポート</h2><section><h3>AIによる要約</h3><p>直近の業務では、会議の論点整理、関係者調整、突発業務対応に継続的に貢献しています。一方で、突発業務増加によりスケジュール影響が発生しており、優先順位判断の支援が必要な状態です。</p></section><section><h3>評価につながる事実</h3><ul><li>会議で目的・論点・次アクションを整理</li><li>関係者との認識ズレを早期に解消</li><li>突発業務に対応</li><li>面談で状況を共有し、次の進め方を合意</li><li>${esc(state.effort||'頑張ったことは未入力')}</li></ul></section><section><h3>成長テーマ</h3><p>優先順位判断／早めの報告・相談／判断軸の言語化</p></section><section><h3>反映情報</h3><p><b>相談目的：</b>${esc(state.meetingPurpose||'未入力')}</p><p><b>会議発言：</b>${esc(state.meetingStatements.join(' / ')||'未入力')}</p><p><b>合意事項：</b>${esc(state.agreement||$('agreementMemo').value)}</p></section><section><h3>上司への確認依頼</h3><p>この内容で評価記録として保存してよいか。上司コメントを追記するか。</p></section>`;}
$('generateReport').onclick=()=>{$('reportCard').innerHTML=reportHtml();$('reportCard').classList.remove('hidden');$('approveReport').classList.remove('hidden');$('editComment').classList.remove('hidden');};$('approveReport').onclick=()=>{$('completeMessage').classList.remove('hidden');};$('editComment').onclick=()=>{$('managerCommentBox').classList.remove('hidden');};$('saveReport').onclick=()=>{state.managerComment=$('managerComment').value;$('completeMessage').classList.remove('hidden');save();};
const questions=['この機能を実際に使いたいと思いましたか？','一番価値を感じた場面はどこですか？','一番違和感があった場面はどこですか？','AIに見られている感覚は、安心でしたか？監視感がありましたか？','上司との関係は良くなりそうですか？','評価への納得感は上がりそうですか？'];
function renderFeedback(){const names=steps.map(s=>s.dataset.title);$('feedbackList').innerHTML=names.map((n,i)=>`<div class="feedback-row"><b>${i+1}. ${n}</b><p>リアクション：${esc((state.feedback[i]||{}).reaction||'未選択')}</p><p>メモ：${esc((state.feedback[i]||{}).memo||'未入力')}</p></div>`).join('');const box=document.querySelector('.final-questions');box.innerHTML='<h2>最後の質問</h2>'+questions.map((q,i)=>`<label for="q${i}">${q}</label><textarea id="q${i}">${esc(state.finalAnswers[i]||'')}</textarea>`).join('')+'<button id="saveFinal" class="primary">回答を保存する</button>';$('saveFinal').onclick=()=>{questions.forEach((_,i)=>state.finalAnswers[i]=$(`q${i}`).value);$('finalToast').hidden=false;save();};}
renderLogs();render();
