const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='aiCoachScheduleDelayPrototype';
const state=Object.assign({step:0,slot:'1時間後 15分',meetingLog:[],scheduleVisible:false,finalSpoken:false},JSON.parse(localStorage.getItem(KEY)||'{}'));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statuses=['相談中','面談提案','資料作成','会議補助','状況補足'];
function input(id,label,ph,val=''){return `<label for="${id}">${label}</label><textarea id="${id}" placeholder="${ph}">${esc(val)}</textarea>`}
function header(app,title,badges=''){return `<header class="work-header"><div><p class="eyebrow">${app}</p><h1>${title}</h1></div><div class="badges">${badges}</div></header>`}
function chat(){return `${header('Work Teams','新サービス企画',state.meetingSet?'<span>AI Coach 3者面談 1時間後</span>':'<span class="alert">資料提出 本日17:00</span>')}<section class="grid"><div class="card"><div class="section-title">チャットログ</div><div class="chat-log"><div class="work-msg"><b>上司</b><span>企画資料、今日中に中間版を見せてもらえますか？</span></div><div class="work-msg"><b>メンバー</b><span>追加調査の依頼が入りました。優先度高めです。</span></div><div class="work-msg"><b>後輩</b><span>すみません、資料の進め方で少し相談できますか？</span></div><div class="work-msg"><b>本人</b><span>確認します。</span></div>${state.step===1?'<div class="work-msg notice"><b>AI Coach</b><span>上司との面談を提案しています</span></div>':''}</div></div><aside><div class="card"><div class="section-title">今日のタスク</div><ul class="task-list"><li>企画資料の中間版作成</li><li>追加調査への対応</li><li>後輩の相談対応</li><li>関係者コメント反映</li></ul></div><div class="card small-card"><div class="section-title">資料提出予定</div><p>本日 17:00 中間版提出</p><p class="pill">現在の見込み：未完了</p>${state.meetingSet?'<p class="pill">AI Coach 3者面談 1時間後</p>':''}</div></aside></section>`}
function calendar(){return `${header('Work Calendar','AI Coach 3者面談','<span>開始：1時間後</span>')}<section class="calendar card"><div class="section-title">予定詳細</div><p><b>会議名：</b>AI Coach 3者面談</p><p><b>開始：</b>1時間後</p><p><b>参加者：</b>本人 / 上司 / AI Coach</p><p><b>目的：</b>${esc(state.purpose||'資料遅れの背景と今後の進め方を相談')}</p></section>`}
function meeting(){return `${header('Work Meeting','AI Coach 3者面談','<span>会議中</span>')}<section class="meeting-screen"><div class="participants"><article><div class="avatar">本</div><b>本人</b></article><article><div class="avatar">上</div><b>上司</b></article><article><div class="avatar">AI</div><b>AI Coach</b></article></div><div class="meeting-body ${state.scheduleVisible?'with-schedule':''}"><div class="card"><div class="section-title">会議ログ</div><div id="meetingLog" class="meeting-log">${renderMeeting()}</div></div>${state.scheduleVisible?schedulePanel():''}</div><div class="meeting-controls"><button>ミュート</button><button>画面共有</button><button>退出</button></div></section>`}
function schedulePanel(){return `<div class="card schedule-wrap"><div class="section-title">1週間のスケジュール可視化</div><div class="schedule-grid">${scheduleCells()}</div><div class="legend"><span class="normal">通常予定</span><span class="doc">資料作成</span><span class="urgent">突発業務</span><span class="junior">後輩相談</span><span class="hidden-work">空白だったが実態あり</span></div><div class="small-card ai-card"><b>AI補足</b><ul><li>空白に見えた時間の多くが、突発業務・後輩相談で埋まっていた</li><li>直近1週間で突発業務：6件</li><li>後輩相談対応：4件</li><li>資料作成に集中できたまとまった時間：2回のみ</li><li>遅れの主因は、本人の怠慢ではなく、差し込み対応と相談対応による作業時間の分断</li></ul></div></div>`}
const times=['9:00','10:00','11:00','13:00','14:00','15:00','16:00','17:00'], days=['月','火','水','木','金'];
const data={
'月-9:00':['normal','会議'],'月-10:00':['doc','資料作成'],'月-11:00':['urgent','追加調査'],'月-14:00':['junior','進め方相談'],'月-16:00':['hidden-work','差し込み対応'],
'火-9:00':['normal','関係者確認'],'火-11:00':['urgent','緊急確認'],'火-13:00':['junior','資料レビュー相談'],'火-15:00':['doc','資料作成'],
'水-10:00':['urgent','差し込み対応'],'水-13:00':['normal','会議'],'水-14:00':['junior','相談対応'],'水-16:00':['hidden-work','追加調査'],
'木-9:00':['normal','関係者確認'],'木-11:00':['urgent','追加調査'],'木-14:00':['junior','進め方相談'],'木-15:00':['hidden-work','緊急確認'],
'金-10:00':['doc','資料作成'],'金-11:00':['urgent','差し込み対応'],'金-14:00':['normal','会議'],'金-16:00':['hidden-work','相談対応']};
function scheduleCells(){let h='<div class="cell head"></div>'+days.map(d=>`<div class="cell head">${d}</div>`).join(''); times.forEach(t=>{h+=`<div class="cell time">${t}</div>`;days.forEach(d=>{const v=data[`${d}-${t}`];h+=`<div class="cell">${v?`<div class="block ${v[0]}">${v[1]}</div>`:''}</div>`})});return h}
function renderMeeting(){return (state.meetingLog||[]).map(m=>`<div class="bubble ${m.role}"><b>${m.role==='ai'?'AI Coach':m.role==='boss'?'上司':'本人'}</b><br>${esc(m.text)}</div>`).join('')}
function reportText(){return `1. 状況\n・企画資料の中間版が予定より遅れ気味\n・${state.consult||'資料が遅れそう'}\n\n2. 背景\n・突発業務が複数発生\n・後輩相談対応が重なった\n\n3. 相談したいこと\n・${state.purpose||'提出範囲をどこまでにするか'}\n・突発業務の優先順位をどう扱うか\n\n4. AIの提案\n・まず判断軸とおすすめ案を先に提出\n・詳細資料は次回更新で補足\n・突発業務は発生時点で優先度確認`}
function slidesPreview(){const made=state.reportMade;return `<section class="card slide-preview"><div class="section-title">Work Slides プレビュー</div><article class="slide-card ${made?'':'empty'}"><h2>スケジュール遅れ相談メモ</h2>${made?`<div class="slide-cards"><div><b>状況</b><p>中間版資料が遅れ気味</p><small>${esc(state.consult||'資料が遅れそう')}</small></div><div><b>背景</b><p>突発業務が複数発生</p><p>後輩相談対応が重なった</p></div><div><b>相談したいこと</b><p>提出範囲の見直し</p><small>${esc(state.purpose||'突発業務の優先順位')}</small></div><div><b>AI提案</b><p>判断軸とおすすめ案を先に提出</p><p>詳細は次回更新で補足</p></div></div>`:`<p class="muted">AI Coachで「資料を作成」を押すと、ここに1枚資料が生成されます。</p>`}</article></section>`}
function calendarAndSlides(){return `${header('Work Calendar / Work Slides','面談設定と相談資料','<span>1時間後 15分</span>')}<section class="split-work"><section class="calendar card"><div class="section-title">今日の予定</div><div class="time-slot muted">14:00　通常作業</div><div class="time-slot selected"><b>1時間後　AI Coach 3者面談</b><span>参加者：本人 / 上司 / AI Coach</span><span>時間：15分</span><span>目的：${esc(state.purpose||'資料遅れの背景と今後の進め方を相談')}</span></div><div class="time-slot muted">17:00　中間版提出</div></section>${slidesPreview()}</section>`}
function setAppName(){const names=['Work Teams','Work Teams','Work Calendar / Work Slides','Work Meeting','Work Meeting'];$('#appName').textContent=names[state.step]||'Work Teams';$$('.rail-item').forEach(b=>{const app=b.dataset.app; b.classList.toggle('active',(state.step<2&&app==='Chat')||(state.step===2&&(app==='Calendar'||app==='Slides'))||(state.step>2&&app==='Meeting'))})}
function renderMain(){setAppName();if(state.step<2)$('#workMain').innerHTML=chat(); else if(state.step===2)$('#workMain').innerHTML=calendarAndSlides(); else $('#workMain').innerHTML=meeting()}
function renderCoach(){state.step=Math.max(0,Math.min(4,state.step));$('#coachStatus').textContent=statuses[state.step];$('#stepCounter').textContent=`${state.step+1} / 5`;$('#prevBtn').disabled=state.step===0;$('#nextBtn').textContent=state.step===4?'最初に戻る':'次へ';const c=$('#coachContent');
if(state.step===0)c.innerHTML=`<h2>遅れを相談</h2><div class="ai-card">提出予定に遅れの兆候があります。状況を整理しますか？</div>${input('consult','今の状況','例：突発業務と後輩相談が重なり、企画資料が遅れています',state.consult||'')}<div class="chips">${['資料が遅れそう','突発業務が多い','後輩相談で時間を使った','上司にどう説明するか迷う'].map(x=>`<button data-chip="${x}">${x}</button>`).join('')}</div><button id="sendConsult">AIに相談する</button>${state.consultReply?`<div class="bubble ai">${esc(state.consultReply)}</div><button id="toProposal">面談提案を見る</button>`:''}`;
if(state.step===1)c.innerHTML=`<h2>上司と1時間後に話しますか？</h2><div class="ai-card">資料の遅れが大きくなる前に、上司と15分だけ状況をすり合わせることをおすすめします。</div><ul><li>提出予定に遅れが出ている</li><li>突発業務と後輩相談が重なっている</li><li>本人の努力や背景が見えにくくなる前に共有した方がよい</li></ul><div class="small-card"><b>候補日時</b><div class="slots">${['1時間後 15分','明日 10:00','明日 15:00'].map(x=>`<button class="slot ${state.slot===x?'selected':''}" data-slot="${x}">${x}</button>`).join('')}</div></div>${input('purpose','上司に相談したいこと','例：資料遅れの背景と、提出範囲の見直しを相談したい',state.purpose||'')}<button id="setMeeting">1時間後に設定する</button><button id="decline" class="ghost">今回は見送る</button>${state.meetingSet?'<div class="small-card complete">1時間後に、本人・上司・AI Coachの3者面談を設定しました。</div><button id="toReport">相談資料を作成する</button>':''}`;
if(state.step===2)c.innerHTML=`<h2>相談資料</h2><div class="ai-card">会議で使う資料を短くまとめます。</div><button id="makeReport">資料を作成</button>${state.reportMade?`<div class="small-card"><pre>${esc(state.reportEdit||reportText())}</pre></div><div class="button-row"><button id="editReport" class="ghost">修正する</button><button id="goMeeting">この資料で会議へ</button></div>`:''}${state.editing?input('reportEdit','相談資料を編集','',state.reportEdit||reportText())+'<button id="saveReport" class="ghost">保存</button>':''}`;
if(state.step===3)c.innerHTML=`<h2>会議補助</h2><div class="ai-card">会議ログを見ながら、必要な時だけ補足します。</div><button id="startMeeting">会議開始</button>${state.meetingStage==='stopped'?'<div class="ai-card">説明が難しそうです。1週間の予定と、空白時間の実態を見せますか？</div><button id="showSchedule">スケジュールを見せる</button>':''}`;
if(state.step===4)c.innerHTML=`<h2>状況を補足</h2><div class="ai-card">予定表だけでは見えない作業も含めて、1週間の実態を整理します。</div>${!state.scheduleVisible?'<button id="showSchedule">スケジュールを見せる</button>':'<button id="nextSpeech">次の発言へ</button>'}${state.finalSpoken?'<div class="small-card complete"><b>相互理解が深まりました</b><ul><li>上司は遅れの背景を理解</li><li>本人は状況を客観データで説明できた</li><li>次に優先する作業範囲が明確になった</li></ul><button id="reset">最初に戻る</button></div>':''}`;
bind()}
function render(){save();renderMain();renderCoach()}
function bind(){ $$('[data-chip]').forEach(b=>b.onclick=()=>{$('#consult').value=b.dataset.chip});$('#sendConsult')?.addEventListener('click',()=>{state.consult=$('#consult').value.trim();state.consultReply=`状況を確認しました。「${state.consult.slice(0,24)||'資料遅れ'}」の背景には、突発業務や後輩相談対応が含まれていそうです。上司と短時間で状況をすり合わせることをおすすめします。`;render()});$('#toProposal')?.addEventListener('click',()=>{state.step=1;render()});$$('.slot').forEach(b=>b.onclick=()=>{state.slot=b.dataset.slot;render()});$('#setMeeting')?.addEventListener('click',()=>{state.purpose=$('#purpose').value.trim();state.meetingSet=true;render()});$('#decline')?.addEventListener('click',()=>{state.step=2;render()});$('#toReport')?.addEventListener('click',()=>{state.step=2;render()});$('#makeReport')?.addEventListener('click',()=>{state.reportMade=true;state.reportEdit=state.reportEdit||reportText();render()});$('#editReport')?.addEventListener('click',()=>{state.editing=true;render()});$('#saveReport')?.addEventListener('click',()=>{state.reportEdit=$('#reportEdit').value;state.editing=false;render()});$('#goMeeting')?.addEventListener('click',()=>{state.step=3;render()});$('#startMeeting')?.addEventListener('click',()=>{state.meetingLog=[{role:'ai',text:'今日は、企画資料の遅れの背景と、今後の進め方を確認します。'},{role:'me',text:'企画資料の中間版が少し遅れています。突発対応などが重なり、予定より作業時間が取れませんでした。'},{role:'boss',text:'突発対応があったのは分かりました。ただ、なぜここまで遅れているのか、もう少し具体的に教えてください。'}];state.meetingStage='stopped';render()});$('#showSchedule')?.addEventListener('click',()=>{state.step=4;state.scheduleVisible=true;render()});$('#nextSpeech')?.addEventListener('click',()=>{state.meetingLog=state.meetingLog.concat([{role:'ai',text:'補足します。予定表上は空いているように見えた時間帯にも、突発業務や後輩相談対応が入っていました。資料作成に集中できたまとまった時間は、直近1週間で2回のみです。'},{role:'boss',text:'なるほど。空いているように見えていた時間にも対応が入っていたんですね。遅れの背景が理解できました。'},{role:'boss',text:'突発対応や後輩相談もしてくれていたなら、そこは労います。まずは資料の判断軸とおすすめ案を優先しましょう。'},{role:'me',text:'ありがとうございます。詳細資料は次回更新で補足します。'},{role:'ai',text:'合意事項として、判断軸とおすすめ案を先に提出、突発業務は発生時点で優先度確認、後輩相談対応も作業実績として記録、で保存します。'}]);state.finalSpoken=true;render()});$('#reset')?.addEventListener('click',()=>{localStorage.removeItem(KEY);location.reload()})}
function next(){state.step=state.step===4?0:state.step+1;render()}function prev(){if(state.step>0){state.step--;render()}}
$('#minimizeBtn').onclick=()=>{$('#coachPanel').classList.add('hidden');$('#coachTab').classList.remove('hidden')};$('#coachTab').onclick=()=>{$('#coachPanel').classList.remove('hidden');$('#coachTab').classList.add('hidden')};$('#nextBtn').onclick=next;$('#skipBtn').onclick=next;$('#prevBtn').onclick=prev;document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev()});
render();
