const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='aiCoachPrototypeV2';
const state=Object.assign({step:0,meetingLog:[],meetingStage:0},JSON.parse(localStorage.getItem(KEY)||'{}'));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statuses=['相談中','記録中','確認中','面談提案中','設定中','相談メモ中','会議補助中','レポート作成中'];
const chatMsgs=[['上司','判断軸だけ先に見せてもらえますか？'],['メンバー','追加調査が入りました。今日中に確認が必要です。'],['本人','優先順位を確認します。'],['通知','追加調査により、資料提出に影響の可能性']];
function input(id,label,ph,val=''){return `<label for="${id}">${label}</label><textarea id="${id}" placeholder="${ph}">${esc(val)}</textarea>`}
function header(app,title,badges=''){return `<header class="work-header"><div><p class="eyebrow">${app}</p><h1>${title}</h1></div><div class="badges">${badges}</div></header>`}
function chat(extra='',task=false,dim=false){$('#workMain').classList.toggle('dim',dim);return `${header('Work Chat','新サービス企画','<span>資料作成中</span><span class="alert">追加調査</span>')}<section class="grid"><div class="card"><div class="section-title">新サービス企画</div><div class="chat-log">${chatMsgs.map(([n,t])=>`<div class="work-msg ${n==='本人'?'me':''} ${n==='通知'?'notice':''}"><b>${n}</b><span>${t}</span></div>`).join('')}${extra}</div></div><aside>${task?taskCard():sideCards()}</aside></section>`}
function sideCards(){return `<div class="card"><div class="section-title">今日の予定</div><ul><li>14:00 論点整理</li><li>15:00 会議準備</li></ul></div>`}
function taskCard(){return `<div class="card"><div class="section-title">今日のタスク</div><ul class="task-list"><li>企画資料の判断軸を整理</li><li>関係者コメントを反映</li><li>追加調査に対応</li></ul></div>`}
function calendar(detail=false){$('#workMain').classList.remove('dim');return `${header('Work Calendar','予定','<span>空き時間あり</span>')}<section class="calendar"><div class="card slot-card"><div class="section-title">今日の予定</div><p class="pill">16:30 空き</p>${state.scheduleDone?'<p class="pill">AI Coach 3者面談</p>':''}</div><div class="card slot-card"><div class="section-title">明日の予定</div><p class="pill">10:00 空き</p><p class="pill">15:00 空き</p></div><div class="card slot-card"><div class="section-title">仮予定</div><p>AI Coach 3者面談</p></div></section>${detail?`<section class="card small-card"><div class="section-title">AI Coach 3者面談</div><p>参加者：本人 / 上司 / AI Coach</p><p>目的：優先順位と資料完成範囲の確認</p></section>`:''}`}
function meeting(){return `${header('Work Meeting','AI Coach 3者面談','<span>会議中</span>')}<section class="meeting-screen"><div class="participants"><article><b>本人</b><span>説明</span></article><article><b>上司</b><span>確認</span></article><article><b>AI Coach</b><span>補助</span></article></div><div class="card"><div class="section-title">会話ログ</div><div id="meetingLog" class="meeting-log">${renderMeeting()}</div></div><div class="meeting-controls"><button>ミュート</button><button>画面共有</button><button>退出</button></div></section>`}
function record(){return `${header('Work Record','成長記録','<span>保存済みログ</span>')}<section class="record-grid"><div class="card"><div class="section-title">今日の面談</div><p>優先順位と資料完成範囲を確認</p><div id="mainSaved">${state.reportSaved?'<div class="small-card saved-note">AI Coach：成長記録を保存しました</div>':''}</div></div><div class="card"><div class="section-title">上司コメント欄</div><p>${esc(state.managerComment||'未保存')}</p></div></section>`}
function renderMain(){let s=state.step; if(s===0)$('#workMain').innerHTML=chat(); if(s===1)$('#workMain').innerHTML=chat('',true); if(s===2)$('#workMain').innerHTML=chat(taskCard(),true,true); if(s===3)$('#workMain').innerHTML=chat('<div class="work-msg notice"><b>AI Coach</b><span>上司との15分面談を提案しています</span></div>'); if(s===4)$('#workMain').innerHTML=calendar(); if(s===5)$('#workMain').innerHTML=calendar(true); if(s===6)$('#workMain').innerHTML=meeting(); if(s===7)$('#workMain').innerHTML=record();}
function renderCoach(){let s=state.step; $('#coachStatus').textContent=statuses[s]; $('#stepCounter').textContent=`${s+1} / 8`; $('#prevBtn').disabled=s===0; $('#nextBtn').textContent=s===7?'最初へ':'次へ'; const c=$('#coachContent');
if(s===0)c.innerHTML=`<h2>相談</h2><div class="ai-card">突発依頼と資料遅れの兆候があります。整理しますか？</div>${input('consult','今困っていることを入力','今困っていることを入力',state.consult||'')}<div class="chips">${['資料が遅れそう','優先順位を相談したい','上司に報告すべきか迷う'].map(x=>`<button data-chip="${x}">${x}</button>`).join('')}</div><button id="sendConsult">送信</button>${state.consultReply?`<div class="bubble ai">${esc(state.consultReply)}</div>`:''}`;
if(s===1)c.innerHTML=`<h2>記録</h2><div class="ai-card">今日の動きを短く残します。</div><div class="small-card"><ul><li>会議で論点整理</li><li>追加調査に対応</li><li>資料作成が遅れ気味</li></ul></div>${input('effort','頑張ったこと','例：会議前に論点を整理した',state.effort||'')}${input('trouble','困ったこと','例：突発対応で時間が足りなかった',state.trouble||'')}<button id="saveRecord">記録する</button>${state.recordSaved?'<div class="toast">記録しました。面談提案の判断材料に使います。</div>':''}`;
if(s===2)c.innerHTML=`<h2>蓄積</h2><div class="ai-card">直近の状態です。</div>${['成果：論点整理が増えています','負荷：突発対応が多めです','相談候補：優先順位のすり合わせ'].map(x=>`<div class="small-card">${x}</div>`).join('')}${bar('成果',75)}${bar('負荷',85)}${bar('迷い',60)}<div class="small-card">相談内容：${esc(state.consult||'未入力')}</div><div class="small-card">困りごと：${esc(state.trouble||'未入力')}</div>`;
if(s===3)c.innerHTML=`<h2>面談提案</h2><div class="ai-card">突発対応と資料遅れが続いています。上司と15分だけ話しますか？</div><ul><li>突発対応が多い</li><li>優先順位で迷っている</li><li>頑張りが見えにくくなる前に共有したい</li></ul><div class="button-row"><button id="acceptMeeting">面談する</button><button id="decline" class="ghost">今はしない</button></div><div id="declineBox" class="${state.declined?'':'hidden'}">${input('declineReason','理由','例：もう少し整理したい',state.declineReason||'')}</div>`;
if(s===4)c.innerHTML=`<h2>設定</h2><div class="ai-card">上司と15分だけ押さえます。</div><div class="slots">${['今日 16:30','明日 10:00','明日 15:00'].map(x=>`<button class="slot ${state.slot===x?'selected':''}" data-slot="${x}">${x}</button>`).join('')}</div>${input('purpose','相談したいこと','例：突発業務が入った時の優先順位',state.purpose||'')}<button id="setSchedule">設定する</button>${state.scheduleDone?`<div class="toast">${esc(state.slot)} に設定しました。</div>`:''}`;
if(s===5)c.innerHTML=`<h2>相談メモ</h2><div class="ai-card">面談前に、話す内容を短く整理します。</div><button id="makeMemo">メモを作成</button>${state.memoMade?memoHtml():''}${state.memoMade?`${input('memoEdit','修正する','',state.memoEdit||memoText())}<button id="saveMemo" class="ghost">修正を保存</button><button id="goMeeting">このメモで面談へ</button>`:''}`;
if(s===6)c.innerHTML=`<h2>会議補助</h2><div class="ai-card">上司から聞かれた内容を、必要に応じて補足します。</div><button id="startMeeting">会議開始</button><div class="small-card">${state.meetingStage>=1?'上司：資料が少し遅れているけど、何が原因ですか？':'開始すると会話ログに表示します。'}</div>${input('meetingInput','あなたならどう答えますか？','例：突発対応が多く、作業時間が分断されました','')}<button id="speak">発言する</button><button id="assist" class="ghost">AIに補足してもらう</button><button id="nextSpeech" class="secondary">次の発言へ</button><button id="finishMeeting">面談を終了</button>`;
if(s===7)c.innerHTML=`<h2>レポート</h2><div class="ai-card">面談内容を成長記録にまとめます。</div><button id="makeReport">レポート作成</button>${state.reportMade?reportHtml():''}${state.reportMade?`${input('managerComment','上司コメント欄','',state.managerComment||'突発対応が多い中でも、論点整理と関係者調整を進めていた点は評価できます。次回は遅れが見えた時点で早めに相談しましょう。')}<div class="button-row"><button id="approve">承認</button><button id="saveReport" class="ghost">保存</button></div>${state.reportSaved?'<div class="toast">成長記録として保存しました。</div>':''}`:''}`;
bind();}
function bar(n,p){return `<div class="bar"><span style="width:${p}%">${n} ${p}%</span></div>`}
function memoText(){return `状況：突発対応が増え、資料作成が遅れ気味\n背景：追加調査や関係者対応が発生\n相談：${state.purpose||'未入力'}\n提案：判断軸とおすすめ案を先に完成させる`}
function memoHtml(){return `<div class="small-card"><ul><li>状況：突発対応が増え、資料作成が遅れ気味</li><li>背景：追加調査や関係者対応が発生</li><li>相談：${esc(state.purpose||'未入力')}</li><li>提案：判断軸とおすすめ案を先に完成させる</li></ul></div>`}
function renderMeeting(){return (state.meetingLog||[]).map(m=>`<div class="bubble ${m.role}"><b>${m.role==='ai'?'AI Coach':m.role==='boss'?'上司':'本人'}</b><br>${esc(m.text)}</div>`).join('')}
function addMeet(role,text){state.meetingLog.push({role,text});save();renderMain()}
function reportHtml(){return `<div class="small-card"><ul class="report-list"><li>貢献：論点整理、関係者調整、突発対応</li><li>背景：突発業務により資料作成に影響</li><li>合意：判断軸とおすすめ案を優先</li><li>次の成長テーマ：早めの報告、優先順位判断</li><li>相談内容：${esc(state.consult)}</li><li>頑張ったこと：${esc(state.effort)}</li><li>困ったこと：${esc(state.trouble)}</li><li>相談したいこと：${esc(state.purpose)}</li><li>本人発言：${esc(state.meetingStatement)}</li></ul></div>`}
function bind(){ $$('[data-chip]').forEach(b=>b.onclick=()=>{$('#consult').value=b.dataset.chip}); $('#sendConsult')?.addEventListener('click',()=>{state.consult=$('#consult').value.trim();state.consultReply=`状況を記録しました。「${state.consult.slice(0,18)}」は、業務量・優先順位の問題として整理します。`;save();render()}); $('#saveRecord')?.addEventListener('click',()=>{state.effort=$('#effort').value.trim();state.trouble=$('#trouble').value.trim();state.recordSaved=true;save();render()}); $('#acceptMeeting')?.addEventListener('click',()=>{state.step=4;render()}); $('#decline')?.addEventListener('click',()=>{state.declined=true;save();render()}); $('#declineReason')?.addEventListener('input',e=>{state.declineReason=e.target.value;save()}); $$('.slot').forEach(b=>b.onclick=()=>{state.slot=b.dataset.slot;save();render()}); $('#setSchedule')?.addEventListener('click',()=>{state.purpose=$('#purpose').value.trim();state.scheduleDone=true;save();render()}); $('#makeMemo')?.addEventListener('click',()=>{state.memoMade=true;state.memoEdit=state.memoEdit||memoText();save();render()}); $('#saveMemo')?.addEventListener('click',()=>{state.memoEdit=$('#memoEdit').value;save();render()}); $('#goMeeting')?.addEventListener('click',()=>{state.step=6;render()}); $('#startMeeting')?.addEventListener('click',()=>{state.meetingLog=[];state.meetingStage=1;addMeet('ai','今日は、遅れの背景と次の進め方を確認します。');addMeet('boss','資料が少し遅れているけど、何が原因ですか？');render()}); $('#speak')?.addEventListener('click',()=>{state.meetingStatement=$('#meetingInput').value.trim(); if(state.meetingStatement)addMeet('me',state.meetingStatement);renderCoach()}); $('#assist')?.addEventListener('click',()=>{addMeet('ai','補足します。突発対応が複数あり、作業時間が分断されています。一方で、会議整理や関係者調整は進んでいます。');state.meetingStage=2;save();renderCoach()}); $('#nextSpeech')?.addEventListener('click',()=>{const seq=['なるほど。背景が分かりました。突発対応もしてくれていたんですね。','相談テーマは、優先順位、資料の完成範囲、報告タイミングです。','今回は判断軸とおすすめ案を優先しましょう。詳細は次の段階で大丈夫です。','合意事項として記録します。']; const roles=['boss','ai','boss','ai']; const i=(state.nextIdx||0); if(i<seq.length){addMeet(roles[i],seq[i]);state.nextIdx=i+1;save();renderCoach()}}); $('#finishMeeting')?.addEventListener('click',()=>{state.step=7;render()}); $('#makeReport')?.addEventListener('click',()=>{state.reportMade=true;save();render()}); $('#approve')?.addEventListener('click',()=>{state.managerComment=$('#managerComment').value;state.reportSaved=true;save();render()}); $('#saveReport')?.addEventListener('click',()=>{state.managerComment=$('#managerComment').value;state.reportSaved=true;save();render()});}
function render(){state.step=Math.max(0,Math.min(7,state.step));save();renderMain();renderCoach()}
function next(){state.step=state.step===7?0:state.step+1;render()} function prev(){if(state.step>0){state.step--;render()}}
$('#minimizeBtn').onclick=()=>{$('#coachPanel').classList.add('hidden');$('#coachTab').classList.remove('hidden')}; $('#coachTab').onclick=()=>{$('#coachPanel').classList.remove('hidden');$('#coachTab').classList.add('hidden')}; $('#nextBtn').onclick=next; $('#skipBtn').onclick=next; $('#prevBtn').onclick=prev; document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev()});
render();
